plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.manuscriptvalidation'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom "io.awspring.cloud:spring-cloud-aws-dependencies:4.1.0"
        mavenBom "org.apache.camel.springboot:camel-spring-boot-bom:4.22.0"
    }
}

dependencies {

    // MongoDB
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'

    // Jackson
    implementation 'com.fasterxml.jackson.core:jackson-databind'

    // Spring Validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // Spring Web
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'

    // AWS SNS
    implementation 'software.amazon.awssdk:sns'

   // AWS SQS
    implementation 'io.awspring.cloud:spring-cloud-aws-starter-sqs'

    // AWS SDK v2
    implementation 'software.amazon.awssdk:s3'
    implementation 'software.amazon.awssdk:sns'
    implementation 'software.amazon.awssdk:sqs'
    implementation 'software.amazon.awssdk:sso'
    

    // Apache Camel
    implementation 'org.apache.camel.springboot:camel-spring-boot-starter'
    implementation 'org.apache.camel.springboot:camel-aws2-sqs-starter'
    implementation 'org.apache.camel.springboot:camel-jackson3-starter'

    // AWS SES ← NEW
    implementation 'software.amazon.awssdk:ses'

    // Development
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

       // Tests
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-mongodb-test'
    testImplementation 'org.junit.jupiter:junit-jupiter-api'
    testImplementation 'org.junit.jupiter:junit-jupiter-engine'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.mockito:mockito-junit-jupiter'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}